// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAy1urU9jfGD7KLSG7-aYsvAUFfIWie0',
    appId: '1:998290689489:web:5caf96f663e6a03fd524f0',
    messagingSenderId: '998290689489',
    projectId: 'campusz-b0a89',
    authDomain: 'campusz-b0a89.firebaseapp.com',
    storageBucket: 'campusz-b0a89.firebasestorage.app',
    measurementId: 'G-BF8SBZ6WD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj-e_hftsGSN85oCNIeHmmw58rp9isetM',
    appId: '1:998290689489:android:17a547cf1930a9bed524f0',
    messagingSenderId: '998290689489',
    projectId: 'campusz-b0a89',
    storageBucket: 'campusz-b0a89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDumvfFTI969DvtIYqNJOfbb1xk05DHue8',
    appId: '1:998290689489:ios:b0bbe38558d380dbd524f0',
    messagingSenderId: '998290689489',
    projectId: 'campusz-b0a89',
    storageBucket: 'campusz-b0a89.firebasestorage.app',
    iosBundleId: 'com.example.untitled11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDumvfFTI969DvtIYqNJOfbb1xk05DHue8',
    appId: '1:998290689489:ios:b0bbe38558d380dbd524f0',
    messagingSenderId: '998290689489',
    projectId: 'campusz-b0a89',
    storageBucket: 'campusz-b0a89.firebasestorage.app',
    iosBundleId: 'com.example.untitled11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsAy1urU9jfGD7KLSG7-aYsvAUFfIWie0',
    appId: '1:998290689489:web:4a312464c8a466e3d524f0',
    messagingSenderId: '998290689489',
    projectId: 'campusz-b0a89',
    authDomain: 'campusz-b0a89.firebaseapp.com',
    storageBucket: 'campusz-b0a89.firebasestorage.app',
    measurementId: 'G-FRF6P80GGR',
  );
}
